# Generated by Django 5.2 on 2025-08-08 20:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0001_initial'),
        ('contracts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_name', models.CharField(max_length=255, verbose_name="Nom de l'événement")),
                ('event_start', models.DateTimeField(verbose_name="Début de l'événement")),
                ('event_end', models.DateTimeField(verbose_name="Fin de l'événement")),
                ('location', models.CharField(max_length=500, verbose_name='Lieu')),
                ('attendees', models.PositiveIntegerField(verbose_name='Nombre de participants')),
                ('notes', models.TextField(blank=True, verbose_name='Notes complémentaires')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date de mise à jour')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='clients.client', verbose_name='Client concerné')),
                ('contract', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='event', to='contracts.contract', verbose_name='Contrat associé')),
            ],
            options={
                'verbose_name': 'Événement',
                'verbose_name_plural': 'Événements',
                'ordering': ['-event_start'],
            },
        ),
    ]
